import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import QueryProvider from "../components/providers/QueryProvider";
import { Toaster } from "react-hot-toast";
// @ts-expect-error Missing types
import "./globals.css";



const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.variable} antialiased`}
      >
        <Toaster />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
